### ISSUE TITLE
feature request for proactive notification about suspicious domain name

### ISSUE THREAD

**Issue by xuchkang171** [liaa/real_domain_name#1]
Instead of getting the real domain name via clicking the icon of this extension while I'm curious about it, it'd be more reasonable for this extension to automatically examining about the suspicious domain name for every page I'm visiting, and prompting user strikingly when something worth noting detected.

**Comment by runningdemo** [comment]
Good point. A pull request is welcome and I will take a look how to do it later :)

**Comment by runningdemo** [comment]
Already support auto detection now.
