### ISSUE TITLE
Fake domain detect approach

### ISSUE THREAD

**Issue by Senorsen** [liaa/real_domain_name#2]
I noticed your approach to detect fake domain name is to find if the domain starts with `xn-`, which means all IDNA encoded domain will be alerted.

![image](https://cloud.githubusercontent.com/assets/4176091/25174735/e3aae1f2-252a-11e7-8384-b2ef9ecd414f.png)

http://xn--fiqs8sirgfmhq98a.xn--zfr164b/

I wonder, if possible, should it detect fake domain names by finding some specified letter in IDNA encoded string?

Thanks.

**Comment by runningdemo** [comment]
I don't see the problem with the current approach, can you be more specific, thank you.

**Comment by gloomy-ghost** [comment]
It basically treats IDNs as second class citizens. There are huge amount of false positives -- image how annoying it would be if you got a warning on every page of a local news website. I think we should either only indicate IDNs with a harmless icon (pageAction would be good), or find a more accurate approach.
